### ISSUE TITLE
No FRS exp gained when defeating a BH

### ISSUE THREAD

**Issue by mikeface** [Thrax989/Project-Phoenix#101]

**Comment by bobvious** [comment]
I'm pretty sure the plan was to disable this to prevent avoid flight clubbing with guild / friendly BH's?

**Comment by mikeface** [comment]
That kind if discourages pvp tho, doesn't it?  I mean, if i get no benefit from defeating a BH, I could just run, wait for my TEF to clear, and go back inside.

**Comment by Ayzoz** [comment]
it always had frs before I would wait and test it after restart. remember we the BH's were also getting the start a gcw battle window on engaging you too and could not manipulate controls.

**Comment by Thrax989** [comment]
This has been patch thank you . https://github.com/Thrax989/Project-Phoenix/commit/26b18a9eb6326aa3467dbc4f3c209bfb102d6c15
