### ISSUE TITLE
Squad Leader buffs not working properly

### ISSUE THREAD

**Issue by zabawakie** [Thrax989/Project-Phoenix#108]
I believe the SL buffs used to work for anyone in the group on the planet. Currently my squad leader buffs only people in the same house, or people outside the house when im outside. I cannot buff people outside while inside. They also do not appear to work planet wide any longer.

**Comment by Thrax989** [comment]
are you in a private house ?

**Comment by zabawakie** [comment]
I am actually getting weird conflicting things here. I am in the buff house in stone haven. My dancer can buff there. But I landed another character on planet and was getting buffs from my SL. But still not getting them for my characters and friends that were fighting right next to me.

**Comment by bobvious** [comment]
This is not a bug.  SL buffs work for players in the group on the same planet that SL is leading.   If the SL is outside, only players outside will get in the buff.   In a cave, dungeon, or house, only players inside with the SL will the receive buffs.
