### ISSUE TITLE
the ?move up command is broken on Lok

### ISSUE THREAD

**Issue by Ayzoz** [Thrax989/Project-Phoenix#116]
/move up command reports "please specify a name before distance and amount" when on planet Lok

tested by multiple people on different accounts and same outcome.

same character can manipulate objects on naboo fine.

**Comment by mikeface** [comment]
Also of note, was not broken for all accounts.  I was able to /move up just fine on Lok.

**Comment by Ayzoz** [comment]
The culprit was an upholstered chair.
