### ISSUE TITLE
Slicing: precision Laser Knives not reporting tool effectiveness

### ISSUE THREAD

**Issue by Ayzoz** [Thrax989/Project-Phoenix#131]
With full experimentation the precision laser knife reports tool effectiveness 0%

**Comment by bobvious** [comment]
Doesn't really matter.  The quality of smuggler supplies has never been in the slicing calculation.   Did it show up before?

**Comment by Ayzoz** [comment]
we tested it absolutely showed a difference between a well made tool and a crappy tool....even though both report 0 effective.

**Comment by bobvious** [comment]
It's not in the code.  Check slicingsessionimplementation.   And, it is operating just like Basilisk, I just tested on a smuggler there.    Precision Laser Knife effectiveness is always zero.   So, it is not a bug.  You could add it to future server ideas.   Quality doesn't matter for weapon upgrade kits and armor upgrade kits either.  Thanks.   Closed.
