### ISSUE TITLE
unable to equip lightsabers

### ISSUE THREAD

**Issue by taznivek** [Thrax989/Project-Phoenix#134]
i bought a 5 th gen lightsaber and i cannot equip it i am master lightsaber it is a double bladed lightsaber and it has a fc 55 and the crystals in it are my own so than i decided to buy a jinsu and the same thing happened

**Comment by Thrax989** [comment]
This has been patched thank you . https://github.com/Thrax989/Project-Phoenix/commit/005b737bd5a399001d545757a1b9f19e230d91e8
