### ISSUE TITLE
lightsaber

### ISSUE THREAD

**Issue by taznivek** [Thrax989/Project-Phoenix#136]
still unable to equip 2 lightsabers i bought one double bladed 5 th gen darth phoebus and one jinsu they both tell me the same message you cannot equip a lightsaber crafted by someone else and yet they where able to sell these can i get some help

**Comment by merik444** [comment]
Server has no gone down since the commit was made that should hopefully fix that issue. For Reference please see this commit

https://github.com/Thrax989/Project-Phoenix/commit/005b737bd5a399001d545757a1b9f19e230d91e8
