### ISSUE TITLE
Cannot wear clothes from different races.

### ISSUE THREAD

**Issue by zabawakie** [Thrax989/Project-Phoenix#71]
**EDIT** title should read, cannot wear clothes from different races, not factions.

I play as a nightsister or something similar, but since the new patch today, I cannot equip clothes from other races. It states I lack the necessary requirements to wear this item.

**Comment by Thrax989** [comment]
This will be addressed once we make the server stable still working on one big server crash bug. All clothing and armor will be able to be worn by all races soon again. This also go for weapons all species will be able to wear them soon again too.

**Comment by Thrax989** [comment]
This has been Updated Thanks for waiting. https://github.com/Thrax989/Project-Phoenix/commit/17ac7fe3024a9e8efa9a4f6dfca4de040ac0c5ce
