### ISSUE TITLE
Harvesters (new made) are using default harvester rates not our boosted rates

### ISSUE THREAD

**Issue by laughingowl** [Thrax989/Project-Phoenix#87]
Have not verified all, but pretty sure all harvesters are defaulting to the 'stock' BERs which seems to be about 1/4th of what old harvesters were (maybe 1/5th).

**Comment by Thrax989** [comment]
This has been patched thank you . https://github.com/Thrax989/Project-Phoenix/commit/c0f18940e039419d4df97200e9ea0dc1aa711ab5
