### ISSUE TITLE
Custom creatures not existing

### ISSUE THREAD

**Issue by laughingowl** [Thrax989/Project-Phoenix#89]
No Elder Krayts (not perma Krayt King)

No Mittens

**Comment by graffix460** [comment]
no battle with ig-88 ackelys ect on tat, borgle gave has borgle bats in it again and not the NPCs

**Comment by bobvious** [comment]
Elder krayts, king, and mittens added to repository.   I'm trying to figure out where the big spawn outside Peepsbuu was add in the code.

**Comment by Thrax989** [comment]
This has been patched thank you . https://github.com/Thrax989/Project-Phoenix/commit/eb5a17e0997e2973ea876ad0100b62e8a98c1954
