### ISSUE TITLE
Force lightening doing no damage

### ISSUE THREAD

**Issue by graffix460** [Thrax989/Project-Phoenix#91]
Force lightening is doing no damage to Mobs

**Comment by graffix460** [comment]
Using force lightening is very slow as it also has a que timer on it. Rancors take 1 damage from lightening as well as krayts

**Comment by laughingowl** [comment]
Update all forces powers that were tweaked are off>

AI is back to being very cheap (per reports)

Also reports the Force Intimidate takes more force and much longer recast time then before

**Comment by Thrax989** [comment]
This has been patched thank you . https://github.com/Thrax989/Project-Phoenix/pull/111/commits/9951df4f207c8e52ba31be88f226c4457f123c06
