### ISSUE TITLE
[BUG] /healenhance

### ISSUE THREAD

**Issue by sygnum** [Thrax989/Project-Phoenix#95]
(This has probably already reported but) This command appears to be bugged for a few of the buffs. Can you please look into this and fix the bug (It does the the error Target player must be person or pet error)

**Comment by Thrax989** [comment]
This has been patched thank you .

**Comment by sygnum** [comment]
This does not appear to be fixed, 
![screenshot0001](https://cloud.githubusercontent.com/assets/13894489/21140912/734c2cc6-c108-11e6-83fd-2b08626e3f41.jpg)

This is my macro
`Macro 3: DocBuff

/:b;
/afk;
/pause .5;
/ui action startChatReply;
/ui action chatCursorHome;
/ui action chatCursorRight;
/ui action chatDelete;
/ui action chatDelete;
/ui action chatEnter;
/pause 1;
/ui action toolbarSlot23;
/macro DocFood;
/pause 8;
/say Beginning buffs now;
/ui action toolbarPane04;
/pause 1;
/healEnhance Health;
/pause 13;
/healEnhance Strength;
/pause 13;
/healEnhance Constitution;
/pause 13;
/healEnhance Action;
/pause 13;
/healEnhance Quickness;
/pause 13;
/healEnhance Stamina;
/pause 1;
/say Your buffs are complete. Happy Hunting, and Thank you for the tip..;
/pause 1;
/say storedroid;
/tar Structure;
/pause 1;
/afk;
/:a;
`
